FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["briza_-/briza_-.csproj", "briza_-/"]
RUN dotnet restore "briza_-/briza_-.csproj"
COPY . .
WORKDIR "/src/briza_-"
RUN dotnet build "briza_-.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "briza_-.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "briza_-.dll"]